const Pieces = [
  { id: 'wrook1', name: 'Rook', color: 'white', value: '♖' },
  { id: 'wknight1', name: 'Knight', color: 'white', value: '♘' },
  { id: 'wbishop1', name: 'Bishop', color: 'white', value: '♗' },
  { id: 'wking', name: 'King', color: 'white', value: '♔' },
  { id: 'wqueen', name: 'Queen', color: 'white', value: '♕' },
  { id: 'wbishop2', name: 'Bishop', color: 'white', value: '♗' },
  { id: 'wknight2', name: 'Knight', color: 'white', value: '♘' },
  { id: 'wrook2', name: 'Rook', color: 'white', value: '♖' },
  { id: 'wpawn1', name: 'Pawn', color: 'white', value: '♙' },
  { id: 'wpawn2', name: 'Pawn', color: 'white', value: '♙' },
  { id: 'wpawn3', name: 'Pawn', color: 'white', value: '♙' },
  { id: 'wpawn4', name: 'Pawn', color: 'white', value: '♙' },
  { id: 'wpawn5', name: 'Pawn', color: 'white', value: '♙' },
  { id: 'wpawn6', name: 'Pawn', color: 'white', value: '♙' },
  { id: 'wpawn7', name: 'Pawn', color: 'white', value: '♙' },
  { id: 'wpawn8', name: 'Pawn', color: 'white', value: '♙' },
  { id: 'bpawn1', name: 'Pawn', color: 'black', value: '♙' },
  { id: 'bpawn2', name: 'Pawn', color: 'black', value: '♙' },
  { id: 'bpawn3', name: 'Pawn', color: 'black', value: '♙' },
  { id: 'bpawn4', name: 'Pawn', color: 'black', value: '♙' },
  { id: 'bpawn5', name: 'Pawn', color: 'black', value: '♙' },
  { id: 'bpawn6', name: 'Pawn', color: 'black', value: '♙' },
  { id: 'bpawn7', name: 'Pawn', color: 'black', value: '♙' },
  { id: 'bpawn8', name: 'Pawn', color: 'black', value: '♙' },
  { id: 'brook1', name: 'Rook', color: 'black', value: '♖' },
  { id: 'bknight1', name: 'Knight', color: 'black', value: '♘' },
  { id: 'bishop1', name: 'Bishop', color: 'black', value: '♗' },
  { id: 'bqueen', name: 'Queen', color: 'black', value: '♔' },
  { id: 'bking', name: 'King', color: 'black', value: '♕' },
  { id: 'bbishop2', name: 'Bishop', color: 'black', value: '♗' },
  { id: 'bknight2', name: 'Knight', color: 'black', value: '♘' },
  { id: 'brook2', name: 'Rook', color: 'black', value: '♖' },
];
export default Pieces;